#!/bin/bash

echo
echo "⚠️ WARNING! INSTALL.SH IS A DESTRUCTIVE OPERATION!"
echo
echo "This script will remove files like ~/.vimrc before symlinking them to this directory."
echo

BASE=$(pwd)
echo "Installing from: $BASE"

echo
echo 'Are you sure you want to continue? (y/n)'
read -r response
if [[ "$response" != "y" && "$response" != "Y" ]]; then
  echo "Install.sh exited without making changes."
  exit
fi

echo "Linking ~/.vimrc"
rm -f $HOME/.vimrc
ln -s $BASE/.rc/.vimrc $HOME/.vimrc

echo "Linking ~/.vim"
if [[ "$OS_MODE" != "TERMUX" ]]; then
  sudo rm -rf $HOME/.vim
else
  rm -rf $HOME/.vim
fi

ln -s $BASE/.vim $HOME/.vim

echo "Linking ~/.bashrc"
if [[ "$OS_MODE" != "TERMUX" ]]; then
  sudo rm -rf $HOME/.bashrc
else
  rm -rf $HOME/.bashrc
fi
ln -s $BASE/.rc/.bashrc $HOME/.bashrc

echo "Linking ~/.profile"
if [[ "$OS_MODE" != "TERMUX" ]]; then
  sudo rm -rf $HOME/.profile
else
  rm -rf $HOME/.profile
fi
ln -s $BASE/.rc/.profile $HOME/.profile

echo "Linking ~/.gitconfig"
if [[ "$OS_MODE" != "TERMUX" ]]; then
  sudo rm -rf $HOME/.gitconfig
else
  rm -rf $HOME/.gitconfig
fi
ln -s $BASE/.rc/.gitconfig $HOME/.gitconfig

echo "Linking ~/.ackrc"
if [[ "$OS_MODE" != "TERMUX" ]]; then
  sudo rm -rf $HOME/.ackrc
else
  rm -rf $HOME/.ackrc
fi
ln -s $BASE/.rc/.ackrc $HOME/.ackrc

mkdir -p ~/bin
cd bin
for DIR in *; do
    echo "Linking ~/bin/$DIR"
    rm -f $HOME/bin/$DIR
    ln -sf $BASE/bin/$DIR $HOME/bin/$DIR
done

if [ ! -d "~/notes" ]; then
  mkdir -p "~/notes"
  echo "Directory '~/notes' created."
else
  echo "Directory '~/notes' already exists."
fi
