#!/bin/bash

./install/backup-bin-scripts
./install/create-symlinks

pkg update
pkg upgrade

# Some packages have alternate names in Termux.
# And Termux does not have sudo.

if [[ "$OS_MODE" != "TERMUX" ]]; then
    sudo apt install python3 ack universal-ctags vim
    sudo apt install  tig pwgen ripgrep fzf tree silversearcher-ag perl
else
    pkg install python3 tig pwgen ripgrep fzf tree silversearcher-ag perl
fi
