#!/bin/bash

# ./install/backup-bin-scripts
# ./install/create-symlinks

pkg update
pkg upgrade

pkg install tig pwgen ripgrep fzf tree silversearcher-ag perl

if [[ "$OS_MODE" != "TERMUX" ]]; then
    pkg install ack universal-ctags vim
fi
